### PR TITLE
feature(keyvault): add validation to read, write and full permissions…

### PR DESCRIPTION
**Pull request by filipefigueredo**
# Description

The main goal of this PR is to add validation to the to read, write and full permissions variables in keyvault mode

# Motivation and Context

Since the documentation [azurerm_key_vault_access_policy] (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy) provides a list of valid values for each type of permission, the idea was to implement validation rules accordingly with the documentation. The validation should cover the following variables:

- kv_secret_permissions_full
- kv_certificate_permissions_full
- kv_secret_permissions_read
- kv_certificate_permissions_read
- kv_secret_permissions_write
- kv_certificate_permissions_write

# How Has This Been Tested?

1. Create a new folder in your computer and copy the storage_account folder to it

2. Create a new tf file (main.tf for example) and add the code below referencing the 'keyvault' module
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.65"
    }
  }

  required_version = ">= 1.0.0"
}

provider "azurerm" {
  features {
  }
}

module "resource_group" {
  source   = "git::github.com/Nmbrs/tf-modules/azure/resource-group"
  name     = "rg-myrg-dev"
  location = "westeurope"
   tags = {
    Country : "NL"
    Squad : "Infra"
    Product : "Internal"
    Environment : "Dev"
  }
}


module "keyvault" {
  source              = "../azure/keyvault"
  name                = "kv-mytest-dev"
  location            = module.resource_group.location
  resource_group_name = module.resource_group.name
  tags = module.resource_group.tags

  writers = ["SG-SquadInfra"]
  readers = ["SG-SquadInfra"]
}
```
3. Run terraform validate and see that the code is valid
```bash
$ terraform validate
```
4. Create a new tf file (main.tf for example) and add the code below:
```hcl
module "resource_group" {
  source   = "git::github.com/Nmbrs/tf-modules/azure/resource-group"
  name     = "rg-myrg-dev"
  location = "westeurope"
   tags = {
    Country : "NL"
    Squad : "Infra"
    Product : "Internal"
    Environment : "Dev"
  }
}


module "keyvault" {
  source              = "../azure/keyvault"
  name                = "kv-mytest-dev"
  location            = module.resource_group.location
  resource_group_name = module.resource_group.name
  tags = module.resource_group.tags
  writers = ["SG-SquadInfra"]
  readers = ["SG-SquadInfra"]
  kv_secret_permissions_full = ["invalid"]
  kv_certificate_permissions_full = ["invalid"]
  kv_secret_permissions_read = ["invalid"]
  kv_certificate_permissions_read = ["invalid"]
  kv_secret_permissions_write = ["invalid"]
  kv_certificate_permissions_write = ["invalid"]
}

```
5. Run terraform validate and see that the code is invalid
```bash
$ terraform validate
```
# Screenshots

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by fargozhu — CHANGES_REQUESTED** [review]
@filipefigueredo we are not exposing the access policy rights to the user, and we shouldn't. Otherwise, we are going back to the complex solution that we had before.

We could move the permissions list into a local.tf instead of variables.

**Comment by filipefigueredo** [comment]
> @filipefigueredo we are not exposing the access policy rights to the user, and we shouldn't. Otherwise, we are going back to the complex solution that we had before.
> 
> We could move the permissions list into a local.tf instead of variables.

Since those variable were declared as input variables, I saw them as "optional" values since they have a default value,  and it sounded flexible because the user could  overwrite the default permissions for each profile if they desire to. The main reasons for creating the validation there was the fact that the user could interact with it

So, just to make sure: we don't want the user to overwrite it in no occasion? If not, I'll be closing this PR, and I'll open an issue

**Comment by fargozhu** [comment]
@filipefigueredo the fact that they were declared as variable may have misled you. We could use this pull request or another one to move it to locals ones instead.

**Comment by filipefigueredo** [comment]
> @filipefigueredo the fact that they were declared as variable may have misled you. We could use this pull request or another one to move it to locals ones instead.

Got it. Thanks. I'll close this PR and open another one with the correct scope

**Pull request closed without merging**
