### PR TITLE
feature(dns_zone): create DNS Zone module

### PR DESCRIPTION
**Pull request by filipefigueredo**
## Description

The main goal of this PR is to create the Azure DNS Zone.
## PR Checklist

Please ensure the following before submitting this PR:

- [X] You complied with the code style of this project.
- [X] You formatted all Terraform configuration files to a canonical format (Hint: `terraform fmt`).
- [X] You validated all Terraform configuration files (Hint: `terraform validate`).
- [X] You executed a speculative plan, showing what actions Terraform would take to apply the current configuration (Hint: `terraform plan`).
- [X] The documentation was updated (`README.md`, `CHANGELOG.md`, etc.).
- [X] Whenever possible, the dependencies were updated to the latest compatible versions.

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix.
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no interface changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes.
- [ ] Other... Please describe:

### What is the new behavior?

- Created the DNS Zone Module
- The module by default adds 1 SOA and 1 NS record by default.
- All DNS records are ignored by the DNS module. It means that they can be managed in different lifecycles using different
 terraform projects
- Added strong validations using regex for the domain name (They are being explained in the README.md).

### How to test it

1. At the root of the `tf-module` repository, create a `main.tf` file with the following code:
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.65"
    }
  }
  required_version = ">= 1.0.0"
}

provider "azurerm" {
  features {

  }
}


module "rg-01" {
  source      = "../tf-modules/azure/resource-group"
  name        = "my_project"
  environment = "Staging"
  country     = "nl"
  squad       = "infra"
  product     = "internal"
}


module "dns_zone" {
  source              = "../tf-modules/azure/dns_zone"
  name                = "mydomain.com"
  resource_group_name = module.rg-01.name
  tags                = module.rg-01.tags
}


output "name" {
  description = "The DNS Zone name."
  value       = module.dns_zone.name
}

output "id" {
  description = "The DNS Zone ID."
  value       = module.dns_zone.id
}

output "max_number_of_record_sets" {
  description = "Maximum number of Records in the zone."
  value       = module.dns_zone.max_number_of_record_sets
}

output "number_of_record_sets" {
  description = "The number of records already in the zone."
  value       = module.dns_zone.number_of_record_sets
}


output "name_servers" {
  description = "A list of values that make up the NS record for the zone."
  value       = module.dns_zone.name_servers
}
```
2. Check if the DNS Zone `mydomain.com` and  `example.co.uk` by validating the code (terraform validate)
3. Test for invalid domains like: `mydomain....com`, `sub1.sub2.sub3.com`, 'thisisaverybigbigbigbigdomainandshouldnotwork.com' and see if the validations block the configurations to be executed.

### Does this PR introduce a breaking change?

- [ ] Yes.
- [X] No.

### Other information

To validate the DNS name I've used the following Regex:
`^(?:[[:alnum:]][a-zA-Z0-9-]+[[:alnum:]]\\.){1,2}(?:[[:alpha:]]{2,6})$`

To better understand it you can see how it works in the following picture:
image

### CODE REVIEW

**Comment by pmmluis** [comment]
Why don't we create the zone in the same module of the DNS records? Instead of breaking the zone from the records, we can do both. If we use this it will only have the zone itself, and the records will be in a different service.

**Review by pmmluis — CHANGES_REQUESTED** [review]
Why don't we create the zone in the same service as the DNS records? Instead of breaking the zone from the records, we can do both. If we use this it will only have the zone itself, and the records will be in a different service.

**Comment by filipefigueredo** [comment]
@pmmluis 

> Why don't we create the zone in the same service as the DNS records? Instead of breaking the zone from the records, we can do both. If we use this it will only have the zone itself, and the records will be in a different service.

I may be wrong, but I took this approach after a conversation that we had with @fargozhu concerning the records: for scenarios when the domain's existence is tied to a single application lifecycle, I must agree that your option is the best fit.  Taking this approach, on the other hand, would lead us to try to replicate the same DNS zone several times in different places in scenarios when we need to add many independent entries (DMARC and multiple apps from separate sources).


Please let me know your thoughts on the matter. Would you like to join us in this discussion, @fargozhu? Your input is much valued here.  ❤️

**Comment by filipefigueredo** [comment]
@pmmluis and @fargozhu, as we discussed I'm gonna rename the module to something like `dns` and this module will capable of handling the logic of the DNS zone and also it can incorporate DNS records

**Comment by fargozhu** [comment]
@filipefigueredo @pmmluis a DNS zone is a domain's bucket for all the DNS records created by the different apps/services that exists or will exist. Place both the DNS zone creation and the records all together would force module's users to open a pull request to the organization DNS service to add records on a specific domain when creating/updating their app/service.

The initial though was to have a DNS main repo where domains and zones are created, and let the organization apps/services to manage their DNS records within an existent DNS zone.

**Comment by pmmluis** [comment]
> 

Yes, that's true but as we discussed, this will still happen, this will serve to have the zone, as well as the records that we need to create outside of a app/service. As you there's some DNS records that we need to have that won't have a service per se e.g: A dmarc, spf or redirect record

**Comment by merou** [comment]
i think we need to be able to support also private dns zones.
Concerning the record sets (A,CNAME...) we can have another module.

So at the service level we call 2 modules:
- dns zone module.
- dns record sets module (this module has the name of the dns zone as param).

**Comment by fargozhu** [comment]
@pmmluis I agree. The organization DNS service can contain both DNS zones and organization records. 

I just want to highlight that organization applications can also create DNS records, on pre-defined DNS zones, within its application life cycle.

**Review by fargozhu — APPROVED** [review]
What is proposed here works fine, but I think we could combine the creation of the DNS private zones within the same module with a flag switch.

**Comment by filipefigueredo** [comment]
I'll write here what was agreed:
- make private DNS support available through the module (will be done in a future PR)
- make the records available through the module (will be done in a future PR)

**Review by pmmluis — APPROVED** [review]

**Pull request merged**
