### PR TITLE
minor cosmetic change

### PR DESCRIPTION
**Pull request by merou**
# Description

# Motivation and Context

# How Has This Been Tested?

# Screenshots

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pmmluis — CHANGES_REQUESTED** [review]
What's the reason for this change? This won't be complaint with our naming convention.

**Comment by merou** [comment]
> What's the reason for this change? This won't be complaint with our naming convention.

This is because from the variables.tf it is easier to see what get applied instead of concatenation from module, e.g:
```hcl
variable "virtual_networks" {
  default = {
    vnet1 = {
      id            = "1"
      prefix        = "vnet-dev-westeu-001"
      address_space = ["10.22.0.0/16"]
    }
  }
}
```
This name is matching what is in excel.
Please update excel sheet with proper name - I was just trying to stick to CAF.

**Comment by pmmluis** [comment]
But won't the concatenation be less error-prone instead of using the variables that we need to set? This way, we just pass the name, and the module does it all, the plan will still show the final value.

**Comment by merou** [comment]
> But won't the concatenation be less error-prone instead of using the variables that we need to set? This way, we just pass the name, and the module does it all, the plan will still show the final value.

The thing is that now when we copy the vnet/subnet from the excel sheet we have to remember that the module is actually appending the first part - so just reading variables.tf i cannot really see what get applied (unless tf plan).

However small detail - if you guys prefer to keep it - I am fine.

**Pull request closed without merging**
